#!/bin/bash 

#NCMP=$(mpc | grep "^\[playing\]" | awk '{print $1}')
#NUM_NCMP=$(mpc | head -1 | wc -c )
#S_NCMP=$(mpc | head -1 | head -c 30)


filter() {
	if [ "$(mpc | grep "^\[playing\]" | awk '{print $1}')" = "[playing]" ];then
    	if [ "$(mpc | head -1 | wc -c )" -lt 30 ];then
        	echo -e "MPD> $(mpc current) "
    	else
        	echo -e "MPD> $(mpc | head -1 | head -c 30)..."
	    fi
	else
    	echo -e "MPD> Pausado "
	fi
}

case $BLOCK_BUTTON in
	1) gmpc | filter ;;  # right click, pause/unpause
	3) mpc toggle  | filter ;;  # right click, pause/unpause
    4) mpc prev    | filter ;;  # scroll up, previous
    5) mpc next    | filter ;;  # scroll down, next
    *) mpc current | filter ;;
esac
